version: "3.7"
services:
  mysql:
    image: mysql:8
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  caddy-php:
    build: php
    working_dir: $PWD
    ports:
      - 2015:2015
    volumes:
      - ./:$PWD

      
volumes:
  mysql-data:
