"""
TSLA Alpha Engine: Risk-Rule Engine
Implements deterministic bounds checking to prevent catastrophic portfolio loss.
"""
import math
from dataclasses import dataclass
from enum import Enum, auto

class PositionType(Enum):
    LONG_CALL = auto()
    LONG_PUT = auto()
    SHORT_CALL = auto()
    SHORT_PUT = auto()
    CALENDAR_SPREAD = auto()
    CREDIT_SPREAD = auto()

class SentimentTrigger(Enum):
    NONE = auto()
    SOCIAL_MEDIA = auto()
    EARNINGS = auto()
    MACRO = auto()

@dataclass(slots=True)
class TradeProposal:
    """
    Represents an impending options transaction generated by the ML layer.
    Using __slots__ via slots=True for hyper-optimized memory layout and garbage collection overhead reduction.
    """
    position_type: PositionType
    dte: int  # Days to Expiration
    days_to_earnings: int
    delta: float  # Option Delta (0.0 to 1.0 magnitude)
    position_pnl: float  # Current PnL if adding to an existing position; 0.0 if new
    action_is_add: bool  # True if this trade adds to an existing position
    kelly_wager_pct: float  # Proposed wager as a percentage of portfolio (0.0 to 1.0)
    sentiment_trigger: SentimentTrigger
    vix_level: float
    spy_trend_bearish: bool

class TradeRejection(Exception):
    """Raised when a trade violates a deterministic risk constraint."""
    pass

class RiskEngine:
    """
    Evaluates ML trade proposals against the Anti-Pattern Database (Inversion).
    """
    
    @staticmethod
    def evaluate_trade(trade: TradeProposal) -> float:
        """
        Validates the proposed trade against known anti-patterns.
        
        Returns:
            float: The approved wager percentage (constrained by the Risk Engine).
            
        Raises:
            TradeRejection: If the trade hits a hard kill-switch constraint.
        """
        wager = trade.kelly_wager_pct

        # AP-001: The Earnings IV Crush
        # Why: Volatility surface collapses post-earnings. Vega decay will overpower Delta gains
        # in naked long positions. We strictly forbid buying premium < 7 days from earnings.
        if trade.days_to_earnings < 7 and trade.position_type in (PositionType.LONG_CALL, PositionType.LONG_PUT):
            raise TradeRejection(f"AP-001: Earnings IV Crush risk. DTE to earnings {trade.days_to_earnings} < 7.")

        # AP-002: Averaging Down on Depleting Assets
        # Why: Options are decaying assets governed by dV/dt (Theta). Adding to losing,
        # short-dated positions geometrically increases risk of ruin as P(ITM) shrinks.
        if trade.action_is_add and trade.position_pnl < 0 and trade.dte < 14:
            raise TradeRejection(f"AP-002: Averaging down on short DTE ({trade.dte} < 14) depleting asset.")

        # AP-003: Far OTM Lottery Ticket Chasing
        # Why: Market makers efficiently price multi-sigma tail risks. Continually buying
        # < 10 delta options guarantees negative expected value over large N due to spread & premium.
        if trade.delta < 0.10:
            if trade.kelly_wager_pct > 0.005:  # 0.5%
                raise TradeRejection("AP-003: Far OTM lottery wager exceeds 0.5% Kelly constraint.")

        # AP-004: Ignoring Macro-Economic Correlation
        # Why: TSLA carries high Beta. Idiosyncratic bullish setups fail in high-VIX bear regimes
        # due to overall liquidity drain in the broader indices.
        if trade.spy_trend_bearish and trade.vix_level > 25.0:
            if trade.position_type == PositionType.LONG_CALL:
                # Apply 50% penalty to wager
                wager *= 0.5

        # AP-005: "Elon Tweet" Reaction Over-Leverage
        # Why: Initial algorithmic volatility on social media spikes causes massive slippage.
        # Mean-reversion frequently stops out over-leveraged trades.
        if trade.sentiment_trigger == SentimentTrigger.SOCIAL_MEDIA:
            # Constrain to Quarter-Kelly
            max_social_wager = 0.25 * trade.kelly_wager_pct
            wager = min(wager, max_social_wager)

        return wager

    @staticmethod
    def calculate_fractional_kelly(win_prob: float, win_loss_ratio: float, fraction: float = 0.25) -> float:
        """
        Calculates the fractional Kelly criterion for position sizing.
        
        Formula: f* = (bp - q) / b
        Where:
            b = win_loss_ratio (odds received)
            p = win_prob (probability of winning)
            q = 1 - p (probability of losing)
            
        Why: Full Kelly (f=1.0) is theoretically optimal for log-wealth growth but assumes perfect
        parameter knowledge. Real-world parameter estimation error necessitates a fractional multiplier
        (typically 0.25 or 0.5) to mathematically eliminate the risk of account ruin (drawdowns approaching 100%).
        """
        if win_loss_ratio <= 0:
            return 0.0
        
        q = 1.0 - win_prob
        f_star = (win_loss_ratio * win_prob - q) / win_loss_ratio
        
        # Non-negative wager only
        optimal_f = max(0.0, f_star)
        return optimal_f * fraction
